### ISSUE TITLE
Wait for blockchain sync on start

### ISSUE THREAD

**Issue by re7eal** [ndidplatform/api#2]
## Issue
When starting a new tendermint node, it will sync/replay all the transactions.

## Possible Solution
Track chain sync status by checking the result returned from calling `/status` to tendermint.

**Comment by re7eal** [comment]
There is no need to wait for sync. tendermint will simply return timeout as a response when calling broadcast_tx while it is syncing.

The only downside is that client will need to wait for some time to get the response saying that the API server fails to do whatever it is that client requested.

**Comment by oatsaysai** [comment]
If send the same transaction to the new node that's not completed sync, it will return timeout as a response but it will have status "syncing": true forever.

**Comment by re7eal** [comment]
Fixed in commit f7473b6
