### ISSUE TITLE
GET /as/service/:service_id response with wrong format

### ISSUE THREAD

**Issue by JirapusNon** [ndidplatform/api#21]
When GET /as/service/:service_id, response format is 
{
    "service_id": "string",
    "url": "string"
    "service_name": "string"
}

It should be (Swagger hub)
{
  "min_ial": 1.1,
  "min_aal": 1,
  "url": "string"
}

**Comment by taneekpet** [comment]
Fixed 7a169da at 4f6c9caf and , wait for merge.
