### ISSUE TITLE
Master Public Key is not registered when start up a new node in docker

### ISSUE THREAD

**Issue by 0x0d01** [ndidplatform/api#30]
## Reproduce Steps
* Start up a new node in docker
* Query to function `GetNodeMasterPublicKey` via Tendermint RPC

## Current Result
* Get `{"master_public_key":""}`

## Expected Result
* Get `{"master_public_key":"<key_in_pem_format>"} `

## Cause
* Typo in start up script `start-api.sh` when setting path to `MASTER_PUBLIC_KEY_PATH`

**Comment by taneekpet** [comment]
Is this already resolved? @0x0d01

**Comment by 0x0d01** [comment]
Yes, in 431a5a97c79eb205d090c68a885638a297d9343e.
